In [10]:
import numpy as np

words = [ 'would', 'you', 'could', 'in', 'the', 'dark', 'i', 'not']
scores = np.array([ 5.38, 6.24, 5.52, 5.50, 4.98, 3.82, 5.92, 3.86])

t1 = 'would you could you in the dark'
t2 = 'i would not could not in the dark'

texts = [t1,t2]

X = np.zeros((2,len(words)))
for i,text in enumerate(texts):
    for word in text.split():
        j = words.index(word)
        X[i,j] += 1
print(X)
np.matmul(X,scores)/np.sum(X,axis=1)

[[1. 2. 1. 1. 1. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 2.]]


array([37.68, 38.84])