
# MATHS7027 Mathematical Foundations of Data Science
## Computer Exercise 5
In this computer exercise, we will learn how to solve systems of equations using `numpy`. We will also explore Eigenvalues, Eigenvectors, and the PageRank algorithm.
## 1. Solving Linear Equations in Python
To get started, let's revisit some of the ideas from the previous computer exercise.

Let's start with a problem from the course material. Solve:  
$$
\begin{align*}
2x + y - z &= 2\\
x + 3y +2z & = 1\\
x + y + z & = 2.
\end{align*}
$$

The solution to this system of equations is $x = 2, y = -1, z = 1$.

We can define $A$ and $\mathbf{b}$ in `numpy` as follows.

In [1]:
import numpy as np

A = np.array([[2,1,-1], [1,3,2], [1,1,1]])
b = np.array([2,1,2])

print("A =",A)
print("b =",b)

A = [[ 2  1 -1]
 [ 1  3  2]
 [ 1  1  1]]
b = [2 1 2]


We can solve the matrix equation $A\mathbf{x} = \mathbf{b}$ by using `np.linalg.inv` and `np.matmul`.

In [2]:
np.matmul(np.linalg.inv(A),b)

array([ 2., -1.,  1.])

This approach is fine, but there is a better way to solve linear equations in Python. We can use `np.linalg.solve` to find the solution directly. Try it in the cell below.

In [3]:
np.linalg.solve(A,b)

array([ 2., -1.,  1.])

This should give you the same answer as before, but why do we need two different ways to do the same thing?

`np.linalg.inv` requires us to invert a matrix, which is computationally *very* slow, whereas `np.linalg.solve` only needs row reductions, which is much faster. We can demonstrate this using the example code below.

We'll create a large matrix, $A$, and a large vector, $\mathbf{b}$, then try to solve the system of equations defined by $A$ and $\mathbf{b}$, first using `np.linalg.solve` and then using `np.linalg.inv`. In each case, we'll use `%time` to measure how long our code takes to run.

First, let's define $A$ and $\mathbf{b}$.

In [41]:
n = 3000 # make A an nxn matrix and b an nx1 vector

big_A = np.identity(n)
big_b = np.ones(n)

Now, let's see how long it takes each of our methods to run.

In [12]:
%time answer = np.linalg.solve(big_A,big_b);

CPU times: user 1.96 s, sys: 180 ms, total: 2.14 s
Wall time: 329 ms


In [17]:
%time answer = np.matmul(np.linalg.inv(big_A),big_b)

CPU times: user 6.22 s, sys: 395 ms, total: 6.61 s
Wall time: 998 ms


In [15]:
A= np.linalg.inv(big_A)

In [22]:
%time answer = np.linalg.inv(big_A)

CPU times: user 6.43 s, sys: 410 ms, total: 6.84 s
Wall time: 1.06 s


In [19]:
%time answer = np.matmul(A,big_b)

CPU times: user 12.1 ms, sys: 1.44 ms, total: 13.5 ms
Wall time: 5.64 ms


In [23]:
%time answer = np.matmul(np.linalg.inv(big_A),big_b)

CPU times: user 6.39 s, sys: 526 ms, total: 6.92 s
Wall time: 978 ms


Which method took longer?

If you're interested, you can try doubling the size (`n`) and seeing how long each method takes. Be careful, though - if you make `n` too large, the slower method will take a *very* long time to run.

## 2. List Comprehension
In a previous exercise, we've seen one of the most clever things you can do in Python - list comprehension. Essentially, this allows us to consolidate a for loop into a single line of code.

Let's start by making a list.

In [21]:
a_list = [0,1,2,3,4,5,6,7,8,9]

List comprehension allows us to apply a function to each element of the list we have created.

In [30]:
# represent each element of the list as a string instead of a number
print([str(x) for x in a_list])

# square each element of the list
print([x**2 for x in a_list])

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


We can also define our own functions and then use list comprehension to apply those functions to the list.

In [29]:
# add 2 to every number in our list
def func(x):
    return x+2

[func(x) for x in a_list]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

Now, let's try something a little more complicated.

The function above takes a list as an input, adds 2 to each element of the list, and then returns the answer.

Can you instead create a function that takes a single number, `x`, as its input, and then returns the list of numbers 0 to 9 *plus* `x`? For example, `func(20)` should return the list \[20,21,22,23,24,25,26,27,28,29\]. It's ok if this takes you some time to figure out, if you need to look something up online, or if you need to ask for help with this.

In [34]:
# define your function here
def func(x):
    return [i for i in range(x,x+10)]

# test it out here
func(20)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

## 3. Using PageRank to Answer Questions
Zachary's karate club is a very famous social network of a karate club at a university. In the 1970s, it was used to study how communities form and break apart (if you are interested, you can read more about Zachary's karate club [here](https://en.wikipedia.org/wiki/Zachary%27s_karate_club), but you don't need to know any of this for the exercise). We'll use the PageRank algorithm to identify the most important people in this network.

We'll be using the file zkc_matrix.csv, which you can download from MyUni.

In [35]:
import pandas as pd

# read the data into Python
karate_club_graph = pd.read_csv("zkc_matrix.csv", index_col=0)
# this records the name of every person in the network
names = karate_club_graph.columns

The network is made up of students (numbered 2 to 33), as well as an administrator (John A.) and a karate instructor (Mr. Hi). Here, we're representing the social network in what's called an adjacency matrix. This adjacency matrix contains a 1 to indicate where there is a link or connection between two people, and a 0 where there is not. Again, you don't need to know too much about what an adjacency matrix is; it's enough to recognise that it is: (a) a matrix; and (b) telling us information about the structure of our social network.

In [36]:
# show the matrix
karate_club_graph

Mr. Hi    2    3    4    5    6    7    8    9   10  ...   25   26  \
Mr. Hi     0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  ...  0.0  0.0   
2          1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0   
3          1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  ...  0.0  0.0   
4          1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0   
5          1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
6          1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
7          1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
8          1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
9          1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
10         0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
11         1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
12         1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
13         1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
14         1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
15         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
16         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
17         0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
18         1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
19         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
20         1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
21         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
22         1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
23         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
24         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0   
25         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0   
26         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0   
27         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
28         0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0   
29         0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
30         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
31         0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
32         1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  1.0   
33         0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0   
John A     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  0.0   

         27   28   29   30   31   32   33  John A  
Mr. Hi  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  
2       0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  
3       0.0  1.0  1.0  0.0  0.0  0.0  1.0     0.0  
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
5       0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
6       0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
7       0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
8       0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
9       0.0  0.0  0.0  0.0  1.0  0.0  1.0     1.0  
10      0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  
11      0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
12      0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
13      0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
14      0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  
15      0.0  0.0  0.0  0.0  0.0  0.0  1.0     1.0  
16      0.0  0.0  0.0  0.0  0.0  0.0  1.0     1.0  
17      0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
18      0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
19      0.0  0.0  0.0  0.0  0.0  0.0  1.0     1.0  
20      0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  
21      0.0  0.0  0.0  0.0  0.0  0.0  1.0     1.0  
22      0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  
23      0.0  0.0  0.0  0.0  0.0  0.0  1.0     1.0  
24      0.0  1.0  0.0  1.0  0

We can convert this matrix to a `numpy` array and start calculating PageRank.

In [42]:
# convert adjacency matrix to array
M = np.array(karate_club_graph)
M = M / M.sum(axis = 0)

In the code above, what do you think the second command is doing to our array `M`?

To find out, you can look at the new matrix `M`. It might also be helpful to remember how a matrix must be set up for PageRank; we covered this in [Week 7 (video only)](https://myuni.adelaide.edu.au/courses/81010/pages/week-7-pagerank-an-explanation) and again in [Week 9](https://myuni.adelaide.edu.au/courses/81010/pages/week-9-application-eigenvectors-and-pagerank).

Recall that in order to solve the PageRank problem, we need to solve $M\mathbf{x} = \mathbf{x}$. It's easier to rearrange this as $(M-I)\mathbf{x} = \mathbf{0}$. Do this using the method shown earlier in this computer exercise - you'll need to make an identity matrix and a column vector of zeros (you may need to look up how to do this; [the `numpy` array creation documentation](https://numpy.org/doc/stable/reference/routines.matlib.html) should be helpful).

In [46]:
np.linalg.det(M) == 0

True

In [45]:
# solve (M-I)x = 0 for x

I = np.identity(len(M))
np.linalg.solve(M-I,np.zeros(len(M)))

array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0.])

Depending on how far you have progressed through Section 5, you may know that this approach is equivalent to finding an Eigenvector for $M$ with Eigenvalue $1$. If you haven't seen this yet, don't worry, it just means that $M\mathbf{x} = \mathbf{x}$. We can use `numpy` to solve general Eigenvalue/Eigenvector problems, too - let's do this now.

In [49]:
results = np.linalg.eig(M)

# this returns all of the eigenvalues and eigenvectors, the following
# command will just pick out the eigenvector that we want (the first one)
eigenvector = results[1][:,0].real

# try comparing this eigenvector to the answer you got for x above
print(results,eigenvector)


(array([ 1.00000000e+00+0.00000000e+00j,  8.67727671e-01+0.00000000e+00j,
        7.12951015e-01+0.00000000e+00j,  6.12686767e-01+0.00000000e+00j,
       -7.14611347e-01+0.00000000e+00j,  3.87769460e-01+0.00000000e+00j,
        3.51007053e-01+0.00000000e+00j,  2.92791798e-01+0.00000000e+00j,
        2.60042011e-01+0.00000000e+00j,  2.29089383e-01+0.00000000e+00j,
        1.77057148e-01+0.00000000e+00j,  1.35167055e-01+0.00000000e+00j,
        9.31839984e-02+0.00000000e+00j, -1.05380839e-01+0.00000000e+00j,
       -1.59299956e-01+0.00000000e+00j, -2.68023547e-01+0.00000000e+00j,
       -6.11909588e-01+0.00000000e+00j, -5.69506603e-01+0.00000000e+00j,
       -3.51778259e-01+0.00000000e+00j, -3.93104541e-01+0.00000000e+00j,
       -4.16915851e-01+0.00000000e+00j, -4.48579382e-01+0.00000000e+00j,
       -4.97030113e-01+0.00000000e+00j, -5.83333333e-01+0.00000000e+00j,
       -7.30360170e-17+1.71007759e-17j, -7.30360170e-17-1.71007759e-17j,
        7.50197763e-17+0.00000000e+00j, -4.7857768

The problem here is that $M\mathbf{x} = \mathbf{x}$ has infinitely many solutions. It's true that $\mathbf{x}=\mathbf{0}$ is one such solution, but it's not a very interesting solution. Unfortunately, `np.linalg.solve` does not handle problems with infinite solutions very well.

If we instead solve our problem as an Eigenvector problem, we can get the solutions we are looking for. In this case, our solution still isn't unique, but that's ok. Remember, because PageRank provides a measure of relative importance, we only need one non-zero solution to see the rank/importance of each person in our network. All other solutions will turn out to be multiples of the solution we have chosen.

Now that we have a solution, we can use it to identify the most important person in the network.

In [50]:
most_import_person = eigenvector.argmax()
print(names[most_import_person])

John A


So who is the most important person (according to PageRank)?

Great! Now, let's try showing all of the PageRank scores using a *bar chart*. We want it to show the relative rank for each person in the network by name. You can find documentation for producing bar charts using `matplotlib` [here](https://matplotlib.org/3.5.1/api/_as_gen/matplotlib.pyplot.bar.html).

*Hint: `plt.xticks(rotation=90)` might be helpful to make the labels in your bar chart easier to read!*

In [61]:
A = np.array([[1,1],
             [1,0]])
x = np.array([1,1])

A*x

array([[1, 1],
       [1, 0]])

In [ ]:
import matplotlib.pyplot as plt

# Make a bar chart of PageRank scores



One final remark before we finish this computer exercise: We've used an example from network science/analysis to explore a little more about linear algebra in Python. Network science is just one area of data science (it's actually one of my favourite areas, and where a lot of my research is focused) - you can find many useful tools and packages (like `networkx`) to do network analysis in Python if you are interested. Even so, a lot of the more interesting and advanced methods you might find in those packages still rely on linear algebra, and we know that a good data scientist should understand *how* their tools work (rather than just how to make them work), so it's good to see linear algebra in action here.